Issue 11 account management rework
Campus-Consult/Personaltool pull request #23
Opened 2020-06-10 14:49 UTC by Yorreck

Closes #11 

Overwrites nearly any of the default identity user management. Users can only login with Campus Consult accounts via AzureAD. With the first external login, a user account will be created with the first name as the username and the email provided by the external login provider. There are no managing options anymore. You can only see your registered username and email and can delete your account, which will delete the user but no related persons or other information.

2020-06-10 16:54 UTC, olohr requested changes
Looks promising, however I think it's better to remove all of the files which are not needed anymore. It creates a lot of noise otherwise and it's harder to see which file handles all the logic and is the important one

2020-06-10 16:54 UTC, olohr commented on Areas/Identity/Pages/Account/ExternalLogin.cshtml
> +            <div class="form-group">
This doesn't seem to be used

2020-06-11 15:15 UTC, Yorreck commented on Areas/Identity/Pages/Account/ExternalLogin.cshtml
> +            <div class="form-group">
This will be used as a fallback if the external provider does not provide name or email infos

2020-06-11 17:21 UTC, olohr requested changes
I still think all pages that have no functionality anymore (because they should be unreachable or contained unwanted functionality such as registering, changing email and password) should be deleted, a codebase without garbage is easier to maintain. I tested deleting them and it returns a 404 and since all of those pages should not be reached anymore that's the expected behavior imo.

2020-06-15 15:18 UTC, Yorreck commented
I removed the obsolet files

2020-06-15 17:10 UTC, olohr approved these changes

2020-06-15 17:11 UTC, merged