Issue 8 create models carreer level
Campus-Consult/Personaltool pull request #25
Opened 2020-06-20 12:00 UTC by LTobor

closes #8

2020-06-20 12:24 UTC, LTobor commented
DataType.Date is missing by the dates. Can I just add this, migrate and update the database and push it?

2020-06-22 11:27 UTC, Yorreck commented
> DataType.Date is missing by the dates. Can I just add this, migrate and update the database and push it?

Yes, you should do this

2020-06-24 14:59 UTC, Yorreck requested changes

2020-06-24 14:59 UTC, Yorreck commented on Models/PersonsCareerLevel.cs
> +using Microsoft.CodeAnalysis;
Wehre did you need this?

2020-06-24 15:31 UTC, LTobor commented on Models/PersonsCareerLevel.cs
> +using Microsoft.CodeAnalysis;
I have no clue, deleted the code line.

2020-06-24 16:02 UTC, Yorreck approved these changes

2020-06-25 09:16 UTC, merged